import { CommonModule } from '@angular/common';
import { HttpClient, HttpClientModule } from '@angular/common/http';
import { Component, inject } from '@angular/core';
import { FormsModule, NgForm } from '@angular/forms';
@Component({
  selector: 'app-update',
  standalone: true,
  imports: [HttpClientModule, CommonModule,FormsModule],
  templateUrl: './update.component.html',
  styleUrls: ['./update.component.css'] 
})
export class UpdateComponent {
  httpClient = inject(HttpClient);
  public data: Array<any> = [];
  public errors: string[] = [];
  validation = false;
  ids: number[] = [];
  editIndex: number | null = null; 
  editedQuestion: any = {}; 

  ngOnInit() {
    this.fetchQuestions(); 
  }

  fetchQuestions() {
    this.httpClient.get('http://localhost:8080/question/AllQuestions')
      .subscribe({
        next: (data: any) => {
          console.log(data);
          this.data = data;
          this.ids = data.map((question: { id: any; }) => question.id);
        },
        error: (err) => console.log(err)
      });
  }

  validateForm(form: NgForm): string[] {
    const errors: string[] = [];

    if (!form.value.question) {
      errors.push('Question is required.');
    }

    if (!form.value.optionA || !form.value.optionB || !form.value.optionC || !form.value.optionD) {
      errors.push('All options (A, B, C, D) are required.');
    }

    if (!form.value.answer) {
      errors.push('Answer is required.');
    } else if (!['A', 'B', 'C', 'D'].includes(form.value.answer)) {
      errors.push('Answer must be one of A, B, C, or D.');
    }

    return errors;
  }

  generateId() {
    let newId: number;
    const generateRandomLong = (): number => {

      return Math.floor(Math.random() * Number.MAX_SAFE_INTEGER);
    };

    do {
      newId = generateRandomLong();
    } while (this.ids.includes(newId));  

    return newId;
  }

  editQuestion(index: number) {
    this.editIndex = index;
    this.editedQuestion = { ...this.data[index] }; 
  }

  saveQuestion() {
    if (this.editIndex !== null) {
      this.httpClient.put(`http://localhost:8080/question/${this.editedQuestion.id}`, this.editedQuestion)
        .subscribe({
          next: () => {
         
            this.data[this.editIndex!] = this.editedQuestion;
            this.editIndex = null; 
          },
          error: (err) => console.log(err)
        });
    }
  }

  onSubmit(form: NgForm): void {
    const autoGeneratedId = this.generateId();

    this.errors = this.validateForm(form);
    if (this.errors.length > 0) {
      this.errors.forEach(error => console.log(error));
      return;
    }

    if (form.valid) {
      this.validation = true;
      const newQuestion = {
        id: autoGeneratedId,
        question: form.value.question,
        optionA: form.value.optionA,
        optionB: form.value.optionB,
        optionC: form.value.optionC,
        optionD: form.value.optionD,
        answer: form.value.answer,
        explanation: form.value.explanation,
      };

      console.log(newQuestion);

      this.httpClient.post('http://localhost:8080/question/add', newQuestion)
        .subscribe({
          next: (response) => {
            console.log('Question added successfully:', response);
            form.reset();
            this.fetchQuestions(); 
          },
          error: (err) => console.log(err)
        });
    }
  }

  cancelEdit() {
    this.editIndex = null;
    this.editedQuestion = {};
  }
}

